VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "DogovorRportStub"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public DogDate As Date
Public DogMonth As String
Public ClientName As String
Public FIO As String
Public Reason As String
Public Client As String
Public Address As String
Public INN As String
Public Account As String
Public KorAccount As String
Public BIK As String
Public Position As String
Public Sign As String
