VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "Allowed_GridMenuItems"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Public IsAdd As Boolean
Public IsEdit As Boolean
Public IsDelete As Boolean
Public IsOpen As Boolean
Public IsRef As Boolean
Public IsBuffer As Boolean
Public IsPrn As Boolean
Public IsCfg As Boolean
Public IsFind As Boolean
Public IsAcc As Boolean
