VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "ModeItem"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Public SName As String
Public Obj1 As Object
Public Obj2 As Object
Public Obj3 As Object
Public B1 As Boolean
Public B2 As Boolean
Public B3 As Boolean
Public B4 As Boolean
Public B5 As Boolean
Public B6 As Boolean


